from _typeshed import Incomplete
from djing.core.Element import Element as Element
from djing.core.Panel import Panel as Panel
from djing.core.ResourceToolElement import ResourceToolElement as ResourceToolElement
from typing import Self

class ResourceTool(Panel):
    element: Incomplete
    def __init__(self) -> None: ...
    def name(self): ...
    def tool_component(self): ...
    def can_see(self, callback) -> Self: ...
    def with_meta(self, meta) -> Self: ...
