from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class ResolvesCards:
    def available_cards(self, request: DjingRequest): ...
    def available_cards_for_detail(self, request: DjingRequest): ...
    def resolve_cards(self, request: DjingRequest): ...
    def cards(self, request: DjingRequest): ...
