# Generated by Django 5.1 on 2024-11-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_inventory', '0012_corridor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='cesmd',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
