from Illuminate.Collections.Collection import Collection as Collection
from djing.core.Http.Requests.DeletionRequest import DeletionRequest as DeletionRequest

class DeleteResourceRequest(DeletionRequest):
    def chunks(self, count, callback): ...
    def deletable_models(self, models: Collection): ...
    def is_for_single_resource(self) -> bool: ...
