from Illuminate.Contracts.Support.JsonSerializable import JsonSerializable

class PartitionResult(JsonSerializable):
    def __init__(self, value, total, group_by_column, label_callback) -> None: ...
    def json_serialize(self): ...
