import abc
from djing.core.Metrics.Metric import Metric as Metric
from typing import Self

class RangedMetric(Metric, metaclass=abc.ABCMeta):
    def ranges(self) -> dict: ...
    def default_range(self, key) -> Self: ...
    def json_serialize(self): ...
