# coding: utf-8

"""
    Xray REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.v10_api_test_get200_response_inner_definition_one_of import V10ApiTestGet200ResponseInnerDefinitionOneOf
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

V10APITESTGET200RESPONSEINNERDEFINITION_ONE_OF_SCHEMAS = ["V10ApiTestGet200ResponseInnerDefinitionOneOf", "str"]

class V10ApiTestGet200ResponseInnerDefinition(BaseModel):
    """
    V10ApiTestGet200ResponseInnerDefinition
    """
    # data type: str
    oneof_schema_1_validator: Optional[StrictStr] = None
    # data type: V10ApiTestGet200ResponseInnerDefinitionOneOf
    oneof_schema_2_validator: Optional[V10ApiTestGet200ResponseInnerDefinitionOneOf] = None
    actual_instance: Optional[Union[V10ApiTestGet200ResponseInnerDefinitionOneOf, str]] = None
    one_of_schemas: Set[str] = { "V10ApiTestGet200ResponseInnerDefinitionOneOf", "str" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = V10ApiTestGet200ResponseInnerDefinition.model_construct()
        error_messages = []
        match = 0
        # validate data type: str
        try:
            instance.oneof_schema_1_validator = v
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: V10ApiTestGet200ResponseInnerDefinitionOneOf
        if not isinstance(v, V10ApiTestGet200ResponseInnerDefinitionOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `V10ApiTestGet200ResponseInnerDefinitionOneOf`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in V10ApiTestGet200ResponseInnerDefinition with oneOf schemas: V10ApiTestGet200ResponseInnerDefinitionOneOf, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in V10ApiTestGet200ResponseInnerDefinition with oneOf schemas: V10ApiTestGet200ResponseInnerDefinitionOneOf, str. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into str
        try:
            # validation
            instance.oneof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.oneof_schema_1_validator
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into V10ApiTestGet200ResponseInnerDefinitionOneOf
        try:
            instance.actual_instance = V10ApiTestGet200ResponseInnerDefinitionOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into V10ApiTestGet200ResponseInnerDefinition with oneOf schemas: V10ApiTestGet200ResponseInnerDefinitionOneOf, str. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into V10ApiTestGet200ResponseInnerDefinition with oneOf schemas: V10ApiTestGet200ResponseInnerDefinitionOneOf, str. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], V10ApiTestGet200ResponseInnerDefinitionOneOf, str]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


