from Illuminate.Http.RequestAdapter import RequestAdapter
from _typeshed import Incomplete
from django.http import HttpRequest as HttpRequest

class DjingRequestAdapter(RequestAdapter):
    request: Incomplete
    def __init__(self, request: HttpRequest) -> None: ...
    def get_url(self): ...
    def get_full_url(self): ...
    def get_method(self): ...
    def get_user(self): ...
    def query_data(self): ...
    def post_data(self): ...
    def files_data(self): ...
    def form_data(self): ...
    def multipart_data(self): ...
    def urlencoded_data(self): ...
    def json_data(self): ...
    def headers_data(self): ...
    def sessions_data(self): ...
    def cookies_data(self): ...
