from _typeshed import Incomplete

console: Incomplete

def ensure_git_repository(): ...
def get_git_diff(): ...
def parse_diff(diff): ...
def style_changes(changes): ...
def display_diff() -> None: ...
