# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.04.232942'

RELEASE_GIT_HEAD = 'fca3eb5f8be08d5fab2e18b45b7281a12e566725'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.12.04.232942dev'
