
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/ol_social_auth:ol_social_auth_package

from setuptools import setup

setup(**{
    'author': 'MIT Office of Digital Learning',
    'description': 'An Open edX plugin implementing MIT social auth backend',
    'include_package_data': True,
    'install_requires': (
        'social-auth-core<5.0.0,>=4.5.4',
    ),
    'keywords': 'Python edx',
    'license': 'BSD-3-Clause',
    'name': 'ol-social-auth',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        '',
        'ol_social_auth',
    ),
    'python_requires': '>=3.8',
    'version': '0.1.0',
    'zip_safe': False,
})
