from typing import Self

class PresentsImages:
    def max_width(self, max_width) -> Self: ...
    def index_width(self, index_width) -> Self: ...
    def detail_width(self, detail_width) -> Self: ...
    def aspect(self, aspect) -> Self: ...
    def rounded(self) -> Self: ...
    def squared(self) -> Self: ...
    def is_rounded(self) -> bool: ...
    def is_squared(self) -> bool: ...
    def image_attributes(self): ...
