# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .module_name import ModuleName
import datetime as dt
import typing
from .attempt_info_union import AttemptInfoUnion
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class Attempt(UniversalBaseModel):
    name: ModuleName
    timestamp: dt.datetime
    attempt_info: typing.Optional[AttemptInfoUnion] = pydantic.Field(alias="AttemptInfo", default=None)
    finding: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
