from Illuminate.Foundation.Http.FormRequest import FormRequest
from djing.core.Http.Requests.InteractsWithResources import InteractsWithResources as InteractsWithResources
from djing.core.Http.Requests.InteractsWithResourcesSelection import InteractsWithResourcesSelection as InteractsWithResourcesSelection

class DjingRequest(FormRequest, InteractsWithResources, InteractsWithResourcesSelection):
    def is_resource_index_request(self): ...
    def is_resource_detail_request(self): ...
    def is_action_request(self): ...
    def is_create_or_attach_request(self) -> bool: ...
    def is_update_or_update_attached_request(self) -> bool: ...
    def request_is(self, name: str): ...
