
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-06T09:49:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ec3cf1e51f3f83615bb54a9fa78d776d48c3ffe",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
