
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-05T14:18:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2cb287f52caf8d6e618542bdfbc0706759bdd21",
 "version": "1.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
