from django.db.models import QuerySet as QuerySet
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class SimplePaginator:
    def __init__(self, query: QuerySet, request: DjingRequest) -> None: ...
    def paginate(self, per_page: int): ...
    def per_page(self): ...
    def page(self): ...
    def start_record(self): ...
    def end_record(self): ...
    def num_pages(self): ...
    def get_collection(self): ...
