# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import datetime as dt
from .request_info import RequestInfo
import typing
from .response_info import ResponseInfo
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class FuzzAttemptInfo(UniversalBaseModel):
    path: str
    timestamp: dt.datetime
    request: RequestInfo
    response: typing.Optional[ResponseInfo] = None
    finding: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
