# coding: utf-8

"""
    RAG as a Service API

    API for managing RAG configurations, integrations, prompt templates, and backtesting.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducky.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lycoai-ducky-sdk.models.generate_response import GenerateResponse

class TestGenerateResponse(unittest.TestCase):
    """GenerateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateResponse:
        """Test GenerateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateResponse`
        """
        model = GenerateResponse()
        if include_optional:
            return GenerateResponse(
                generation_id = '',
                generated_text = '',
                documents_used = [
                    {"next_cursor":"next_cursor","metadata":{"key":"metadata"},"content_chunks":["content_chunks","content_chunks"],"document_id":"document_id"}
                    ],
                config_used = lycoai-ducky-sdk.models.config_used.config_used()
            )
        else:
            return GenerateResponse(
        )
        """

    def testGenerateResponse(self):
        """Test GenerateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
