# coding: utf-8

"""
    RAG as a Service API

    API for managing RAG configurations, integrations, prompt templates, and backtesting.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducky.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lycoai-ducky-sdk.api.webapp_only_api import WebappOnlyApi


class TestWebappOnlyApi(unittest.TestCase):
    """WebappOnlyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebappOnlyApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_key_0(self) -> None:
        """Test case for create_api_key_0

        Create API Key
        """
        pass

    def test_delete_api_key_0(self) -> None:
        """Test case for delete_api_key_0

        Delete API Key
        """
        pass

    def test_get_organizations_0(self) -> None:
        """Test case for get_organizations_0

        Get Organizations
        """
        pass

    def test_list_api_keys_0(self) -> None:
        """Test case for list_api_keys_0

        Get API Keys
        """
        pass

    def test_sign_in_0(self) -> None:
        """Test case for sign_in_0

        User Sign In
        """
        pass


if __name__ == '__main__':
    unittest.main()
