# coding: utf-8

"""
    RAG as a Service API

    API for managing RAG configurations, integrations, prompt templates, and backtesting.

    The version of the OpenAPI document: 1.0.0
    Contact: support@ducky.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lycoai-ducky-sdk.models.integration_added_response import IntegrationAddedResponse

class TestIntegrationAddedResponse(unittest.TestCase):
    """IntegrationAddedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationAddedResponse:
        """Test IntegrationAddedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationAddedResponse`
        """
        model = IntegrationAddedResponse()
        if include_optional:
            return IntegrationAddedResponse(
                integration_id = ''
            )
        else:
            return IntegrationAddedResponse(
        )
        """

    def testIntegrationAddedResponse(self):
        """Test IntegrationAddedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
