# Generated by Django 3.2.13 on 2022-07-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
