# Generated by Django 3.2.13 on 2023-07-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_inventory', '0009_auto_20230731_1842'),
        ('apps_events', '0004_event_record_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apps_inventory.asset'),
            preserve_default=False,
        ),
    ]
