# Generated by Django 3.2.13 on 2023-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_events', '0005_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_file',
            field=models.FileField(blank=True, upload_to='events'),
        ),
    ]
