# coding: utf-8

"""
    Fireblocks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.6.2
    Contact: support@fireblocks.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fireblocks.models.withdraw_request_dto import WithdrawRequestDto


class TestWithdrawRequestDto(unittest.TestCase):
    """WithdrawRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WithdrawRequestDto:
        """Test WithdrawRequestDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WithdrawRequestDto`
        """
        model = WithdrawRequestDto()
        if include_optional:
            return WithdrawRequestDto(
                id = 'b70701f4-d7b1-4795-a8ee-b09cdb5b850f',
                fee = '7',
                fee_level = 'MEDIUM',
                tx_note = 'withdraw request id b70701f4-d7b1-4795-a8ee-b09cdb5b850d #ETH'
            )
        else:
            return WithdrawRequestDto(
                id = 'b70701f4-d7b1-4795-a8ee-b09cdb5b850f',
        )
        """

    def testWithdrawRequestDto(self):
        """Test WithdrawRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
