from _typeshed import Incomplete
from django.db.models import QuerySet as QuerySet
from djing.core.Contracts.FilterableField import FilterableField as FilterableField
from djing.core.Fields.Field import Field as Field
from djing.core.Fields.FieldFilterable import FieldFilterable as FieldFilterable
from djing.core.Fields.Filters.DateTimeFilter import DateTimeFilter as DateTimeFilter
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from typing import Self

class DateTime(Field, FieldFilterable, FilterableField):
    component: str
    def __init__(self, name, attribute: Incomplete | None = None, resolve_callback: Incomplete | None = None) -> None: ...
    def make_filter(self, request: DjingRequest): ...
    def min(self, value) -> Self: ...
    def max(self, value) -> Self: ...
    def step(self, step) -> Self: ...
    def resolve_default_value(self, request: DjingRequest): ...
    def fill_attribute_from_request(self, request: DjingRequest, request_attribute, model, attribute): ...
    def serialize_for_filter(self): ...
    def json_serialize(self): ...
