from djing.core.Facades.Djing import Djing as Djing
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class Authorizable:
    @classmethod
    def authorizable(cls) -> type: ...
    def authorize_to_view_any(self, request: DjingRequest): ...
    @classmethod
    def authorized_to_view_any(cls, request: DjingRequest): ...
    def authorize_to_view(self, request: DjingRequest): ...
    def authorized_to_view(self, request: DjingRequest): ...
    @classmethod
    def authorize_to_create(self, request: DjingRequest): ...
    @classmethod
    def authorized_to_create(cls, request: DjingRequest): ...
    def authorize_to_replicate(self, request: DjingRequest): ...
    def authorized_to_replicate(self, request: DjingRequest): ...
    def authorize_to_update(self, request: DjingRequest): ...
    def authorized_to_update(self, request: DjingRequest): ...
    def authorize_to_delete(self, request: DjingRequest): ...
    def authorized_to_delete(self, request: DjingRequest): ...
    def authorized_to_restore(self, request: DjingRequest): ...
    def authorized_to_force_delete(self, request: DjingRequest): ...
    def authorize_to(self, request: DjingRequest, ability): ...
    def authorized_to(self, request: DjingRequest, ability): ...
