from django.db.models import QuerySet as QuerySet
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class PerformsQueries:
    def index_query(self, request: DjingRequest, query: QuerySet): ...
    def detail_query(self, request: DjingRequest, query: QuerySet): ...
    def edit_query(self, request: DjingRequest, query: QuerySet): ...
