from Illuminate.Contracts.Support.JsonSerializable import JsonSerializable
from djing.core.Facades.Djing import Djing as Djing
from djing.core.Makeable import Makeable as Makeable
from typing import Self

class URL(Makeable, JsonSerializable):
    def __init__(self, url, remote: bool = False) -> None: ...
    @classmethod
    def remote(cls, url) -> Self: ...
    def get(self): ...
    def active(self): ...
    def json_serialize(self): ...
