from _typeshed import Incomplete
from compendiumscribe.model import Concept as Concept, Domain as Domain, Topic as Topic
from openai import OpenAI as OpenAI

cache: Incomplete

def research_domain(domain_name: str, llm_client: OpenAI, online_llm_client: OpenAI) -> Domain: ...
def enhance_domain(llm_client: OpenAI, domain: str) -> str: ...
def create_topics_to_research(llm_client: OpenAI, domain: str) -> list[str]: ...
def create_research_questions(llm_client: OpenAI, domain: str, topic: str) -> list[str]: ...
def answer_research_question(online_llm_client: OpenAI, question: str) -> str: ...
def generate_concept_name_from_answer(llm_client: OpenAI, answer: str) -> str: ...
def create_additional_concept_questions(llm_client: OpenAI, answer: str, question: str) -> list[str]: ...
def generate_keywords(llm_client: OpenAI, answer: str) -> list[str]: ...
def generate_prerequisites(llm_client: OpenAI, answer: str) -> list[str]: ...
def generate_topic_summary(llm_client: OpenAI, topic: Topic) -> str: ...
def generate_domain_summary(llm_client: OpenAI, domain: Topic) -> str: ...
