from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Http.Requests.QueriesResources import QueriesResources as QueriesResources
from djing.core.Metrics.Metric import Metric as Metric
from djing.core.Resource import Resource as Resource

class MetricRequest(DjingRequest, QueriesResources):
    request_name: str
    def metric(self): ...
    def detail_metric(self): ...
    def available_metrics(self): ...
    def available_metrics_for_detail(self): ...
