from Illuminate.Contracts.Support.JsonSerializable import JsonSerializable
from _typeshed import Incomplete
from typing import Self

class ActionResponse(JsonSerializable):
    data: Incomplete
    def __init__(self, data: Incomplete | None = None) -> None: ...
    @classmethod
    def success(cls, message) -> Self: ...
    @classmethod
    def danger(cls, message) -> Self: ...
    @classmethod
    def redirect(cls, url) -> Self: ...
    @classmethod
    def open_in_new_tab(cls, url) -> Self: ...
    @classmethod
    def visit(cls, url) -> Self: ...
    def json_serialize(self): ...
