# This file should be always locked in Gitlab by the
# user responsible of maintaining this list.

# Put here the list of user's emails allowed to use the 'Login As' feature

allowed_users = [
    "adrian@tinybird.co",
    "aitana@tinybird.co",
    "al@tinybird.co",
    "alrocar@tinybird.co",
    "alex@tinybird.co",
    "alejandro@tinybird.co",
    "anaguerrero@tinybird.co",
    "antoniocarlon@tinybird.co",
    "asun@tinybird.co",
    "ariel@tinybird.co",
    "bete@tinybird.co",
    "dpaneda@tinybird.co",
    "dan@tinybird.co",
    "david.margulies@tinybird.co",
    "eclbg@tinybird.co",
    "esther@tinybird.co",
    "gonzalo@tinybird.co",
    "ienriquez@tinybird.co",
    "irene@tinybird.co",
    "ivan@tinybird.co",
    "jakub@tinybird.co",
    "javi@tinybird.co",
    "jcalvo@tinybird.co",
    "jcontesti@tinybird.co",
    "jgoizueta@tinybird.co",
    "jkrawiec@tinybird.co",
    "jlmadurga@tinybird.co",
    "jmedina@tinybird.co",
    "jordi@tinybird.co",
    "jorge@tinybird.co",
    "jose@tinybird.co",
    "jose.mimbrero@tinybird.co",
    "jmserrano@tinybird.co",
    "jvilaseca@tinybird.co",
    "paco@tinybird.co",
    "pastori@tinybird.co",
    "ramiro@tinybird.co",
    "rmoreno@tinybird.co",
    "rbarbadillo@tinybird.co",
    "rochoa@tinybird.co",
    "saleiva@tinybird.co",
    "vvelarde@tinybird.co",
]
