# Generated by Django 3.2.13 on 2022-07-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetevaluationmodel',
            name='cesmd',
            field=models.CharField(default='CE58658', max_length=7),
            preserve_default=False,
        ),
    ]
