# Generated by Django 3.2.13 on 2023-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_inventory', '0007_auto_20230731_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
