from djing.core.AuthorizedToSee import AuthorizedToSee as AuthorizedToSee
from djing.core.Element import Element as Element
from djing.core.Facades.Djing import Djing as Djing
from djing.core.HasMenu import HasMenu as HasMenu
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Makeable import Makeable as Makeable
from djing.core.Menu.MenuItem import MenuItem as MenuItem

class Dashboard(Element, AuthorizedToSee, Makeable, HasMenu):
    def name(self): ...
    def label(self): ...
    def uri_key(self): ...
    def menu(self, request: DjingRequest): ...
    def show_refresh_button(self): ...
