from Illuminate.Collections.Collection import Collection as Collection
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class ResolvesFilters:
    def available_filters(self, request: DjingRequest): ...
    def resolve_filters(self, request: DjingRequest): ...
    def resolve_filters_from_fields(self, request: DjingRequest): ...
    def filters(self, request: DjingRequest): ...
