from _typeshed import Incomplete

class InertiaApplication:
    package_path: Incomplete
    middlewares: Incomplete
    def __init__(self) -> None: ...
    def add_middleware(self, middleware): ...
    def run(self) -> None: ...
    def key_exist(self, key) -> bool: ...
    def get_template_dirs(self) -> list: ...
    def get_static_dirs(self) -> list: ...
    @property
    def django_breeze_settings(self): ...
