from Illuminate.Collections.Collection import Collection
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Makeable import Makeable as Makeable

class ActionCollection(Collection, Makeable):
    def authorized_to_see_on_table_row(self, request: DjingRequest): ...
    def authorized_to_see_on_index(self, request: DjingRequest): ...
    def authorized_to_see_on_detail(self, request: DjingRequest): ...
