from _typeshed import Incomplete
from djing.core.Actions.Action import Action as Action
from djing.core.Fields.FieldCollection import FieldCollection as FieldCollection
from djing.core.Http.Requests.ActionRequest import ActionRequest as ActionRequest

class DispatchAction:
    request: Incomplete
    action: Incomplete
    fields: Incomplete
    handle_callback: Incomplete
    def __init__(self, request: ActionRequest, action: Action, fields: FieldCollection) -> None: ...
    def dispatch(self): ...
    def handle_standalone(self): ...
    def handle_request(self): ...
    def for_models(self, models): ...
