# coding: utf-8

"""
    Xray REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rest_api_success_response import RestApiSuccessResponse

class TestRestApiSuccessResponse(unittest.TestCase):
    """RestApiSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestApiSuccessResponse:
        """Test RestApiSuccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestApiSuccessResponse`
        """
        model = RestApiSuccessResponse()
        if include_optional:
            return RestApiSuccessResponse(
                test_exec_issue = openapi_client.models.rest_api_success_response_test_exec_issue.RestApiSuccessResponse_testExecIssue(
                    id = '', 
                    key = '', 
                    self = '', ),
                test_issues = openapi_client.models.rest_api_success_response_test_issues.RestApiSuccessResponse_testIssues(
                    success = [
                        openapi_client.models.rest_api_success_response_test_issues_success_inner.RestApiSuccessResponse_testIssues_success_inner(
                            id = '', 
                            key = '', 
                            self = '', 
                            test_version_id = 56, )
                        ], 
                    error = [
                        openapi_client.models.rest_api_success_response_test_issues_error_inner.RestApiSuccessResponse_testIssues_error_inner(
                            test_definition = '', 
                            messages = [
                                ''
                                ], )
                        ], ),
                test_warnings = [
                    ''
                    ],
                test_run_warnings = [
                    openapi_client.models.rest_api_success_response_test_run_warnings_inner.RestApiSuccessResponse_testRunWarnings_inner(
                        test_run_id = 56, 
                        test_key = '', 
                        test_execution_key = '', 
                        warning_collection = [
                            ''
                            ], )
                    ],
                message = ''
            )
        else:
            return RestApiSuccessResponse(
                test_exec_issue = openapi_client.models.rest_api_success_response_test_exec_issue.RestApiSuccessResponse_testExecIssue(
                    id = '', 
                    key = '', 
                    self = '', ),
        )
        """

    def testRestApiSuccessResponse(self):
        """Test RestApiSuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
