# coding: utf-8

"""
    Xray REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.test_get200_response_inner_definition_one_of_steps_inner_step import TestGet200ResponseInnerDefinitionOneOfStepsInnerStep

class TestTestGet200ResponseInnerDefinitionOneOfStepsInnerStep(unittest.TestCase):
    """TestGet200ResponseInnerDefinitionOneOfStepsInnerStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestGet200ResponseInnerDefinitionOneOfStepsInnerStep:
        """Test TestGet200ResponseInnerDefinitionOneOfStepsInnerStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestGet200ResponseInnerDefinitionOneOfStepsInnerStep`
        """
        model = TestGet200ResponseInnerDefinitionOneOfStepsInnerStep()
        if include_optional:
            return TestGet200ResponseInnerDefinitionOneOfStepsInnerStep(
                raw = '',
                rendered = ''
            )
        else:
            return TestGet200ResponseInnerDefinitionOneOfStepsInnerStep(
        )
        """

    def testTestGet200ResponseInnerDefinitionOneOfStepsInnerStep(self):
        """Test TestGet200ResponseInnerDefinitionOneOfStepsInnerStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
