# coding: utf-8

"""
    Xray REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.test_get200_response_inner_definition_one_of_steps_inner import TestGet200ResponseInnerDefinitionOneOfStepsInner

class TestTestGet200ResponseInnerDefinitionOneOfStepsInner(unittest.TestCase):
    """TestGet200ResponseInnerDefinitionOneOfStepsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestGet200ResponseInnerDefinitionOneOfStepsInner:
        """Test TestGet200ResponseInnerDefinitionOneOfStepsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestGet200ResponseInnerDefinitionOneOfStepsInner`
        """
        model = TestGet200ResponseInnerDefinitionOneOfStepsInner()
        if include_optional:
            return TestGet200ResponseInnerDefinitionOneOfStepsInner(
                id = 56,
                index = 56,
                step = openapi_client.models._test_get_200_response_inner_definition_one_of_steps_inner_step._test_get_200_response_inner_definition_oneOf_steps_inner_step(
                    raw = '', 
                    rendered = '', ),
                data = openapi_client.models._test_get_200_response_inner_definition_one_of_steps_inner_step._test_get_200_response_inner_definition_oneOf_steps_inner_step(
                    raw = '', 
                    rendered = '', ),
                result = openapi_client.models._test_get_200_response_inner_definition_one_of_steps_inner_step._test_get_200_response_inner_definition_oneOf_steps_inner_step(
                    raw = '', 
                    rendered = '', ),
                attachements = [
                    ''
                    ]
            )
        else:
            return TestGet200ResponseInnerDefinitionOneOfStepsInner(
        )
        """

    def testTestGet200ResponseInnerDefinitionOneOfStepsInner(self):
        """Test TestGet200ResponseInnerDefinitionOneOfStepsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
