# coding: utf-8

"""
    DeviceServer

    DeviceServer API  # noqa: E501

    The version of the OpenAPI document: 1.1.9
    Contact: david@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import DeviceServer
from DeviceServer.models.button_state import ButtonState  # noqa: E501
from DeviceServer.rest import ApiException

class TestButtonState(unittest.TestCase):
    """ButtonState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ButtonState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = DeviceServer.models.button_state.ButtonState()  # noqa: E501
        if include_optional :
            return ButtonState(
                state = True
            )
        else :
            return ButtonState(
        )

    def testButtonState(self):
        """Test ButtonState"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
