from _typeshed import Incomplete
from django.db.models import QuerySet as QuerySet
from djing.core.Contracts.FilterableField import FilterableField as FilterableField
from djing.core.Filters.Filter import Filter as BaseFilter
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class Filter(BaseFilter):
    field: Incomplete
    def __init__(self, field: FilterableField) -> None: ...
    def name(self): ...
    def key(self): ...
    def apply(self, request: DjingRequest, query: QuerySet, value): ...
    def serialize_field(self): ...
    def json_serialize(self): ...
