from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Resource import Resource as Resource
from typing import Self

class HasDownload:
    def disable_downloads(self) -> Self: ...
    def download(self, download_response_callback) -> Self: ...
    def to_download_response(self, request: DjingRequest, resource: Resource): ...
