from djing.core.Query.ApplyFilter import ApplyFilter as ApplyFilter

class FilterDecoder:
    def __init__(self, filter_string, available_filters=[]) -> None: ...
    def filters(self): ...
    def decode_from_base64_string(self, filter_string): ...
