# Copyright (c) 2023-2024 Datalayer, Inc.
#
# Datalayer License

"""Reserved handles."""


RESERVED_HANDLES = {
    "administrator": 1,
    "about": 1,
    "api": 1,
    "auth": 1,
    "blog": 1,
    "business": 1,
    "clouder": 1,
    "codefeed": 1,
    "corporate": 1,
    "course": 1,
    "data": 1,
    "dataset": 1,
    "dashboard": 1,
    "datalab": 1,
    "discover": 1,
    "doc": 1,
    "explore": 1,
    "explorer": 1,
    "favorite": 1,
    "feed": 1,
    "info": 1,
    "issue": 1,
    "item": 1,    
    "jupyter": 1,
    "jupyterhub": 1,
    "jupyterlab": 1,
    "jupyterpool": 1,
    "kernel": 1,
    "lab": 1,
    "ldap": 1,
    "leaderboard": 1,
    "library": 1,
    "login": 1,
    "logout": 1,
    "me": 1,
    "note": 1,
    "notebook": 1,
    "null": 1,
    "org": 1,
    "organization": 1,
    "privacy": 1,
    "private": 1,
    "project": 1,
    "profile": 1,
    "space": 1,
    "public": 1,
    "reboot": 1,
    "release": 1,
    "releasenote": 1,
    "reset": 1,
    "school": 1,
    "service": 1,
    "setting": 1,
    "sign": 1,
    "signin": 1,
    "signup": 1,
    "cell": 1,
    "solr": 1,
    "sourcefeed": 1,
    "team": 1,
    "term": 1,
    "tos": 1,
    "type": 1,
    "trending": 1,
    "undefined": 1,
    "user": 1,
    "void": 1,
    "support": 1,
    "system": 1,
    "version": 1,
}
