class BuildInfo:  # pylint: disable=too-few-public-methods
    python_version = '3.10.15'
    os_name = 'posix:ubuntu'
    version = '1.0.7'
    git_sha = '80fa8dcd6c2f7acc77c515f2b74affa646b26e03'
    git_branch = 'master'
    git_uncommitted = [
        ' M iuv/test_iuv_logger.py',
        ' M iuv/test_iuv_report.py',
        'R  medver_pytest/lib/.gitignore -> medver_pytest/.gitignore',
        ' M medver_pytest/__init__.py',
        'R  medver_pytest/lib/cfg.py -> medver_pytest/cfg.py',
        'RM medver_pytest/lib/cli.py -> medver_pytest/cli.py',
        'R  medver_pytest/lib/constants.py -> medver_pytest/constants.py',
        'R  medver_pytest/lib/constants_version.py -> medver_pytest/constants_version.py',
        'R  medver_pytest/lib/harness.py -> medver_pytest/harness.py',
        'R  medver_pytest/lib/iuv/__init__.py -> medver_pytest/iuv/__init__.py',
        'RM medver_pytest/lib/iuv/iuv.py -> medver_pytest/iuv/iuv.py',
        'RM medver_pytest/lib/iuv/iuv_data.py -> medver_pytest/iuv/iuv_data.py',
        'RM medver_pytest/lib/iuv/iuv_requirements.py -> medver_pytest/iuv/iuv_requirements.py',
        'R  medver_pytest/lib/log/logger.py -> medver_pytest/log/logger.py',
        'R  medver_pytest/lib/log/logger_stdout.py -> medver_pytest/log/logger_stdout.py',
        'R  medver_pytest/lib/os_specific.py -> medver_pytest/os_specific.py',
        'R  medver_pytest/lib/protocol.py -> medver_pytest/protocol.py',
        'R  medver_pytest/lib/report/__init__.py -> medver_pytest/report/__init__.py',
        'R  medver_pytest/lib/report/common/__init__.py -> medver_pytest/report/common/__init__.py',
        'RM medver_pytest/lib/report/common/footer.py -> medver_pytest/report/common/footer.py',
        'R  medver_pytest/lib/report/common/gen_base_docx.py -> medver_pytest/report/common/gen_base_docx.py',
        'R  medver_pytest/lib/report/common/gen_base_minhtml.py -> medver_pytest/report/common/gen_base_minhtml.py',
        'R  medver_pytest/lib/report/common/gen_base_pdf.py -> medver_pytest/report/common/gen_base_pdf.py',
        'R  medver_pytest/lib/report/common/gen_base_txt.py -> medver_pytest/report/common/gen_base_txt.py',
        'RM medver_pytest/lib/report/common/header.py -> medver_pytest/report/common/header.py',
        'R  medver_pytest/lib/report/common/page_details.py -> medver_pytest/report/common/page_details.py',
        'R  medver_pytest/lib/report/common/page_info.py -> medver_pytest/report/common/page_info.py',
        'R  medver_pytest/lib/report/protocol/__init__.py -> medver_pytest/report/protocol/__init__.py',
        'R  medver_pytest/lib/report/protocol/gen_tp_base.py -> medver_pytest/report/protocol/gen_tp_base.py',
        'R  medver_pytest/lib/report/protocol/gen_tp_docx.py -> medver_pytest/report/protocol/gen_tp_docx.py',
        'R  medver_pytest/lib/report/protocol/gen_tp_minhtml.py -> medver_pytest/report/protocol/gen_tp_minhtml.py',
        'R  medver_pytest/lib/report/protocol/gen_tp_pdf.py -> medver_pytest/report/protocol/gen_tp_pdf.py',
        'R  medver_pytest/lib/report/protocol/gen_tp_txt.py -> medver_pytest/report/protocol/gen_tp_txt.py',
        'R  medver_pytest/lib/report/report.py -> medver_pytest/report/report.py',
        'R  medver_pytest/lib/report/summary/__init__.py -> medver_pytest/report/summary/__init__.py',
        'R  medver_pytest/lib/report/summary/gen_summary_base.py -> medver_pytest/report/summary/gen_summary_base.py',
        'R  medver_pytest/lib/report/summary/gen_summary_docx.py -> medver_pytest/report/summary/gen_summary_docx.py',
        'R  medver_pytest/lib/report/summary/gen_summary_minhtml.py -> medver_pytest/report/summary/gen_summary_minhtml.py',
        'R  medver_pytest/lib/report/summary/gen_summary_pdf.py -> medver_pytest/report/summary/gen_summary_pdf.py',
        'R  medver_pytest/lib/report/summary/gen_summary_txt.py -> medver_pytest/report/summary/gen_summary_txt.py',
        'R  medver_pytest/lib/report/trace_matrix/__init__.py -> medver_pytest/report/trace_matrix/__init__.py',
        'R  medver_pytest/lib/report/trace_matrix/gen_trace_matrix_base.py -> medver_pytest/report/trace_matrix/gen_trace_matrix_base.py',
        'R  medver_pytest/lib/report/trace_matrix/gen_trace_matrix_docx.py -> medver_pytest/report/trace_matrix/gen_trace_matrix_docx.py',
        'R  medver_pytest/lib/report/trace_matrix/gen_trace_matrix_minhtml.py -> medver_pytest/report/trace_matrix/gen_trace_matrix_minhtml.py',
        'R  medver_pytest/lib/report/trace_matrix/gen_trace_matrix_pdf.py -> medver_pytest/report/trace_matrix/gen_trace_matrix_pdf.py',
        'R  medver_pytest/lib/report/trace_matrix/gen_trace_matrix_txt.py -> medver_pytest/report/trace_matrix/gen_trace_matrix_txt.py',
        'RM medver_pytest/lib/requirements.py -> medver_pytest/requirements.py',
        'R  medver_pytest/lib/result_formatter.py -> medver_pytest/result_formatter.py',
        'R  medver_pytest/lib/result_summary.py -> medver_pytest/result_summary.py',
        'R  medver_pytest/lib/services.py -> medver_pytest/services.py',
        'RM medver_pytest/lib/status_info.py -> medver_pytest/status_info.py',
        'R  medver_pytest/lib/stdout_logger.py -> medver_pytest/stdout_logger.py',
        'RM medver_pytest/lib/storage/storage.py -> medver_pytest/storage/storage.py',
        'R  medver_pytest/lib/storage/storage_dev.py -> medver_pytest/storage/storage_dev.py',
        'R  medver_pytest/lib/storage/storage_file_base.py -> medver_pytest/storage/storage_file_base.py',
        'R  medver_pytest/lib/storage/storage_shared_drive.py -> medver_pytest/storage/storage_shared_drive.py',
        'RM medver_pytest/lib/summary.py -> medver_pytest/summary.py',
        'RM medver_pytest/lib/trace_matrix.py -> medver_pytest/trace_matrix.py',
        'RM medver_pytest/lib/utils.py -> medver_pytest/utils.py',
        'R  medver_pytest/lib/verifier.py -> medver_pytest/verifier.py',
        'R  medver_pytest/lib/view/__init__.py -> medver_pytest/view/__init__.py',
        'R  medver_pytest/lib/view/dlg_base.py -> medver_pytest/view/dlg_base.py',
        'R  medver_pytest/lib/view/dlg_manual_action.py -> medver_pytest/view/dlg_manual_action.py',
        'R  medver_pytest/lib/view/dlg_manual_verify.py -> medver_pytest/view/dlg_manual_verify.py',
        'R  medver_pytest/lib/view/view.py -> medver_pytest/view/view.py',
        'MM tools/pyproject_template.toml',
        ' M ut/mocks/mock_protocol.py',
        ' M ut/test_ut_cfg.py',
        ' M ut/test_ut_cli.py',
        ' M ut/test_ut_harness.py',
        ' M ut/test_ut_page_details.py',
        ' M ut/test_ut_requirements.py',
        ' M ut/test_ut_result_summary.py',
        ' M ut/test_ut_storage.py',
        ' M ut/test_ut_utils.py',
        ' M ut/test_ut_verify_delta.py',
        ' M ut/test_ut_verify_delta_pct.py',
        ' M xplat.cfg',
        '?? medver_pytest/lib/build_info.py',
        '?? medver_pytest/lib/constants_version.py',
        '?? medver_pytest/log/__init__.py',
        '?? medver_pytest/storage/__init__.py',
    ]
    git_unpushed = [
    ]
