from Illuminate.Foundation.Console.Command import Command

class InstallCommand(Command):
    name: str
    description: str
    def handle(self) -> None: ...
    def response(self) -> None: ...
    def install_djing_service_provider(self) -> None: ...
    def publish_config(self) -> None: ...
    def publish_dashboard(self) -> None: ...
    def publish_resource(self) -> None: ...
