# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .app_fingerprint_resource_type import AppFingerprintResourceType
import pydantic
import typing
from .app_fingerprint_resource_info import AppFingerprintResourceInfo
from .app_fingerprint_config import AppFingerprintConfig
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class AppFingerprintReport(UniversalBaseModel):
    resourse_type: AppFingerprintResourceType = pydantic.Field(alias="resourseType")
    resourses: typing.Optional[typing.List[AppFingerprintResourceInfo]] = None
    config: AppFingerprintConfig
    errors: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            extra = pydantic.Extra.allow
