import psychopy.core
from _typeshed import Incomplete
from collections.abc import Generator

def nested_iteritems(d) -> Generator[Incomplete]: ...
def nested_deepkeys(d) -> Generator[Incomplete]: ...
def nested_keys(d, keys=[]) -> Generator[Incomplete, Incomplete]: ...
def maxdepth_keys(d, depth: int = 10, deepest: bool = False): ...
def nested_get(d, keys): ...
def nested_set(d, keys, value) -> None: ...
def nested_pop(d, keys): ...
async def lazy_time(clock): ...
def parse_calls(call_list, clock: psychopy.core.Clock | None = None): ...
def get_nearest_f(target: float, framerate: float) -> float: ...
def flip_state(t, target_t, keymask, framerate): ...
