from typing import Optional

class KuiperError(BaseException):
    start: Optional[int]
    end: Optional[int]
    ...

class KuiperCompileError(KuiperError): ...
class KuiperRuntimeError(KuiperError): ...

class KuiperExpression(object):
    def run(self, input: str) -> str: ...
    def run_multiple_inputs(self, inputs: list[str]) -> str: ...

def compile_expression(expression: str, inputs: list[str]) -> KuiperExpression: ...
