from Illuminate.Support.Facades.Validator import Validator
from Illuminate.Validation.ValidationResponse import ValidationResponse as ValidationResponse
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Resource import Resource as Resource

class PerformsValidation:
    @classmethod
    def validate_for_creation(cls, request: DjingRequest) -> ValidationResponse: ...
    @classmethod
    def validator_for_creation(cls, request: DjingRequest) -> Validator: ...
    @classmethod
    def rules_for_creation(cls, request: DjingRequest): ...
    @classmethod
    def validate_for_update(cls, request: DjingRequest, resource: Resource = None): ...
    @classmethod
    def validator_for_update(cls, request: DjingRequest, resource: Resource = None) -> Validator: ...
    @classmethod
    def rules_for_update(cls, request: DjingRequest, resource: Resource = None): ...
    @classmethod
    def format_rules(cls, request: DjingRequest, rules={}): ...
