from Illuminate.Collections.Collection import Collection
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Makeable import Makeable as Makeable
from djing.core.Resource import Resource as Resource

class ResourceCollection(Collection[type[Resource]], Makeable):
    def authorized(self, request: DjingRequest): ...
    def searchable(self): ...
    def grouped(self): ...
    def available_for_navigation(self, request: DjingRequest): ...
    def grouped_for_navigation(self, request: DjingRequest): ...
