from typing import Self

class HasHelpText:
    def help(self, help_text: str) -> Self: ...
    def get_help_text(self) -> str: ...
    def help_width(self, help_width: str | int) -> Self: ...
    def get_help_width(self) -> str | int: ...
