import abc
from abc import abstractmethod
from djing.core.Card import Card as Card
from djing.core.Facades.Djing import Djing as Djing
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Metrics.HasHelpText import HasHelpText as HasHelpText
from typing import Any

class Metric(Card, HasHelpText, metaclass=abc.ABCMeta):
    def resolve(self, request: DjingRequest): ...
    def only_on_detail(self): ...
    def name(self) -> str: ...
    def uri_key(self) -> str: ...
    def key(self): ...
    def get_resolver(self, request: DjingRequest): ...
    @abstractmethod
    def calculate(self, request: DjingRequest, model: Any = None): ...
    def json_serialize(self): ...
