from django.db.models import base as base
from djing.core.Actions.ActionCollection import ActionCollection as ActionCollection
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class ResolvesActions:
    def resolve_actions(self, request: DjingRequest): ...
    def actions(self, request: DjingRequest): ...
    @classmethod
    def defaults_with(cls, actions): ...
    @classmethod
    def default_actions(cls): ...
    def available_actions(self, request: DjingRequest): ...
    def available_actions_on_index(self, request: DjingRequest): ...
    def available_actions_on_detail(self, request: DjingRequest): ...
    def available_actions_on_table_row(self, request: DjingRequest): ...
