from _typeshed import Incomplete

CONFIG_DIR: Incomplete
yaml: Incomplete

def init_config() -> None: ...
def ensure_config_exists(): ...
def load_config(): ...
def save_config(config, show_message: bool = True) -> None: ...
def load_token(): ...
def save_token(token: str): ...
