from djing.core.Djing import Djing as Djing
from djing.core.Providers.DjingCoreServiceProvider import DjingCoreServiceProvider as DjingCoreServiceProvider

def load_django() -> None: ...
def djing_application(): ...
