from Illuminate.Contracts.Support.JsonSerializable import JsonSerializable
from djing.core.AuthorizedToSee import AuthorizedToSee as AuthorizedToSee
from djing.core.Facades.Djing import Djing as Djing
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Makeable import Makeable as Makeable
from djing.core.Metable import Metable as Metable

class Filter(AuthorizedToSee, Makeable, Metable, JsonSerializable):
    component: str
    def name(self): ...
    def key(self): ...
    def default(self): ...
    def options(self, request: DjingRequest): ...
    def get_component(self): ...
    def json_serialize(self) -> dict: ...
