# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from unitycatalog_client_preview.models.create_function import CreateFunction

class CreateFunctionRequest(BaseModel):
    """
    CreateFunctionRequest
    """
    function_info: CreateFunction = Field(...)
    __properties = ["function_info"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateFunctionRequest:
        """Create an instance of CreateFunctionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of function_info
        if self.function_info:
            _dict['function_info'] = self.function_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateFunctionRequest:
        """Create an instance of CreateFunctionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateFunctionRequest.parse_obj(obj)

        _obj = CreateFunctionRequest.parse_obj({
            "function_info": CreateFunction.from_dict(obj.get("function_info")) if obj.get("function_info") is not None else None
        })
        return _obj


