# coding: utf-8

"""
    Unity Catalog API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class FunctionDependency(BaseModel):
    """
    A function that is dependent on a SQL object.  # noqa: E501
    """
    function_full_name: StrictStr = Field(default=..., description="Full name of the dependent function, in the form of __catalog_name__.__schema_name__.__function_name__.")
    __properties = ["function_full_name"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FunctionDependency:
        """Create an instance of FunctionDependency from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FunctionDependency:
        """Create an instance of FunctionDependency from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FunctionDependency.parse_obj(obj)

        _obj = FunctionDependency.parse_obj({
            "function_full_name": obj.get("function_full_name")
        })
        return _obj


