from .independent_cascade import IndependentCascade
from .linear_threshold import LinearThreshold
from .triggering import Triggering
from .decreasing_cascade import DecreasingCascade
from .sp_f2dlt import SemiProgressiveFriendFoeDynamicLinearThreshold
from .np_f2dlt import NonProgressiveFriendFoeDynamicLinearThreshold