import pathspec
from _typeshed import Incomplete

FILE_TYPES: Incomplete

def load_gitignore_patterns(root_folder: str) -> list[str]: ...
def should_include_path(file_path: str, spec: pathspec.PathSpec) -> bool: ...
def find_readme(root_folder: str) -> str: ...
def flatten_repo(root_folder: str, output_folder: str = None, repo_name: str = None) -> None: ...
