from _typeshed import Incomplete
from djing.core.Fields.Filters.TextFilter import TextFilter as TextFilter
from djing.core.Fields.Text import Text as Text
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest

class Email(Text):
    component: str
    def __init__(self, name: str = 'Email', attribute: str = 'email', resolve_callback: Incomplete | None = None) -> None: ...
    def make_filter(self, request: DjingRequest): ...
    def serialize_for_filter(self): ...
    def json_serialize(self): ...
