from _typeshed import Incomplete
from djing.core.Element import Element as Element
from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from djing.core.Resource import Resource as Resource
from typing import Self

class FieldElement(Element):
    panel: Incomplete
    assigned_panel: Incomplete
    def hide_from_index(self, callback: bool = True) -> Self: ...
    def hide_from_detail(self, callback: bool = True) -> Self: ...
    def hide_when_creating(self, callback: bool = True) -> Self: ...
    def hide_when_updating(self, callback: bool = True) -> Self: ...
    def show_on_index(self, callback: bool = True) -> Self: ...
    def show_on_detail(self, callback: bool = True) -> Self: ...
    def show_on_creating(self, callback: bool = True) -> Self: ...
    def show_on_updating(self, callback: bool = True) -> Self: ...
    def is_shown_on_update(self, request: DjingRequest, resource: Resource): ...
    def is_shown_on_index(self, request: DjingRequest, resource: Resource): ...
    def is_shown_on_detail(self, request: DjingRequest, resource: Resource): ...
    def is_shown_on_creation(self, request: DjingRequest): ...
    def only_on_index(self): ...
    def only_on_detail(self): ...
    def only_on_forms(self): ...
    def except_on_forms(self): ...
    def json_serialize(self): ...
