from _typeshed import Incomplete
from djing.core.Fields.Text import Text as Text

class URL(Text):
    component: str
    def __init__(self, name, attribute: Incomplete | None = None, resolve_callback: Incomplete | None = None) -> None: ...
    def resolve(self, resource, attribute: Incomplete | None = None) -> None: ...
    def copyable(self) -> None: ...
