from djing.core.Cards.Help import Help as Help
from djing.core.Dashboard import Dashboard as Dashboard

class Main(Dashboard):
    def name(self): ...
    def uri_key(self): ...
    def cards(self): ...
