class BuildInfo:  # pylint: disable=too-few-public-methods
    python_version = '3.10.15'
    os_name = 'posix:ubuntu'
    version = '0.0.1'
    git_uncommitted = [
        'A  .gitignore',
        'A  .gitmodules',
        'A  .idea/.gitignore',
        'A  .idea/inspectionProfiles/Project_Default.xml',
        'A  .idea/inspectionProfiles/profiles_settings.xml',
        'A  .idea/misc.xml',
        'A  .idea/modules.xml',
        'A  .idea/test-dev-toml.iml',
        'A  LICENSE.txt',
        'A  README.md',
        'A  do_check',
        'A  do_clean',
        'A  do_cpip_update',
        'A  do_doc',
        'A  do_env',
        'A  do_install',
        'A  do_lint',
        'A  do_post_ver',
        'A  do_publish',
        'A  do_subm_update',
        'A  do_update',
        'A  do_ut',
        'A  do_ver',
        'A  doc/test_process.md',
        'A  doc/version_info.md',
        'A  doit',
        'AM pyproject.toml',
        'A  pytest.ini',
        'A  sample/__init__.py',
        'A  sample/app.py',
        'A  sample/main.py',
        'A  setup.ini',
        'A  test_dev_toml/__init__.py',
        'A  test_dev_toml/lib/.gitignore',
        'A  test_dev_toml/lib/__init__.py',
        'A  test_dev_toml/lib/constants_version.py',
        'A  test_dev_toml/lib/main.py',
        'A  tools/install/__init__.py',
        'A  tools/install/do_install_macos',
        'A  tools/install/do_install_msys2',
        'A  tools/install/do_install_ubu',
        'A  tools/install/do_subm_install_macos',
        'A  tools/install/do_subm_install_ubu',
        'AM tools/requirements.txt',
        'A  tools/set_env.sh',
        'A  tools/setup_template.py',
        'A  tools/version_info.json',
        'Am tools/xplat_utils',
        'A  xplat.cfg',
    ]
