from djing.core.Http.Requests.DjingRequest import DjingRequest as DjingRequest
from typing import Any, Self

class HandlesValidation:
    def get_creation_rules(self, request: DjingRequest) -> dict[Any, Any]: ...
    def get_update_rules(self, request: DjingRequest) -> dict[Any, Any]: ...
    def get_rules(self, request: DjingRequest) -> dict[Any, Any]: ...
    def rules(self, *rules) -> Self: ...
    def creation_rules(self, *rules) -> Self: ...
    def update_rules(self, *rules) -> Self: ...
    def validation_key(self) -> str: ...
